### PR TITLE
Do not add pretty_errors as a requirement

### PR DESCRIPTION
**Pull request by 183amir**
pretty_errors is only a debug requirement https://github.com/Lightning-AI/torchmetrics/blob/bfcd4b0e5bfa1256ef9c142956a86df57542a668/requirements/debug.txt installing this package will change the traceback output of python as soon as torchmetrics is imported: https://github.com/Lightning-AI/torchmetrics/blob/bfcd4b0e5bfa1256ef9c142956a86df57542a668/src/torchmetrics/__init__.py#L18. It was so difficult to find out what was changing tracebacks in my script.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by 183amir** [comment]
@conda-forge-admin, please rerender

**Review by Borda — APPROVED** [review]

**Comment by RaulPPelaez** [comment]
This broke a feedstock build that uses torchmetrics: https://github.com/conda-forge/torchmd-net-feedstock/pull/24
I get this error when testing:
```shell
import: 'torchmdnet'
import: 'torchmdnet'
+ pip check
torchmetrics 1.4.0 requires pretty-errors, which is not installed.
```

**Comment by 183amir** [comment]
I suggest removing this dependency from torch metrics completely. You don't want your Python errors to randomly change without knowing what's going on. It's extremely annoying and very difficult to find the culprit.

**Comment by RaulPPelaez** [comment]
This seems indeed like a strange dependency for torchmetrics. The error seems to be in the pip scripts, since it is pip check complaining.
Perhaps the problem is this PR not being in a release yet? https://github.com/Lightning-AI/torchmetrics/pull/2527

**Comment by Borda** [comment]
> Perhaps the problem is this PR not being in a release yet? [Lightning-AI/torchmetrics#2527](https://github.com/Lightning-AI/torchmetrics/pull/2527)

That was not released yet... But we can push it if there is such issue...

**Comment by RaulPPelaez** [comment]
I reckon it should be at least added as a patch in this feedstock, mine is not the only feedstock that's going to start requiring pretty_errors as an explicit dependency otherwise.

**Pull request merged**
